version: 2.1

orbs:
  go: circleci/go@1.11.0

jobs:
  test:
    docker:
      - image: cimg/go:1.22
    environment:
      GO111MODULE: "on"
    steps:
      - checkout
      - run:
          name: Tidy modules
          command: |
            go mod tidy
      - run:
          name: Run tests (flaky enabled)
          command: |
            go test -v ./...

workflows:
  test_suite:
    jobs:
      - test